[FIX] Log warnings
druidoo/FoodCoops pull request #123
Opened 2020-04-10 14:23 UTC by ajayjaviya

Task : https://www.druidoo.io/web#id=2053&action=361&active_id=28&model=project.task&view_type=form&menu_id=237

2020-04-14 08:01 UTC, ivantodorovich requested changes
`WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (category_print_id, print_category_id) of product.product() have the same label: Print Category.`

Are we sure this is not a migration mistake? It's weird we have two fields with the same intention.
product_print_category was migrated and probably severly changed. Maybe this is something we didn't see?

2020-04-14 08:01 UTC, ivantodorovich commented on purchase_package_qty/models/stock_move_line.py
> +        digits=dp.get_precision('Product Unit of Measure'))
In odoo source they don't use `dp.get_precision`.
I think we can just remove it (and also the import)

https://github.com/odoo/odoo/blob/a36a693733579e1e8bdaa3aa00fcc482c6299acf/addons/stock/models/stock_move_line.py#L32

https://github.com/odoo/odoo/blob/a36a693733579e1e8bdaa3aa00fcc482c6299acf/addons/stock/models/stock_move_line.py#L33

2020-04-14 08:21 UTC, ajayjaviya commented
> `WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (category_print_id, print_category_id) of product.product() have the same label: Print Category.`
> 
> Are we sure this is not a migration mistake? It's weird we have two fields with the same intention.
> product_print_category was migrated and probably severly changed. Maybe this is something we didn't see?

print_category_id field is in `coop_default_pricetag` module (
https://github.com/druidoo/FoodCoops/blob/12.0/coop_default_pricetag/models/product_template.py#L148) but I am not sure about it's use

2020-04-14 08:51 UTC, ivantodorovich commented
> > `WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (category_print_id, print_category_id) of product.product() have the same label: Print Category.`
> > Are we sure this is not a migration mistake? It's weird we have two fields with the same intention.
> > product_print_category was migrated and probably severly changed. Maybe this is something we didn't see?
> 
> print_category_id field is in `coop_default_pricetag` module (
> https://github.com/druidoo/FoodCoops/blob/12.0/coop_default_pricetag/models/product_template.py#L148) but I am not sure about it's use

Can you test and check it out?
I think it's probably a mistake

2020-04-14 09:31 UTC, ajayjaviya commented
> > > `WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (category_print_id, print_category_id) of product.product() have the same label: Print Category.`
> > > Are we sure this is not a migration mistake? It's weird we have two fields with the same intention.
> > > product_print_category was migrated and probably severly changed. Maybe this is something we didn't see?
> > 
> > 
> > print_category_id field is in `coop_default_pricetag` module (
> > https://github.com/druidoo/FoodCoops/blob/12.0/coop_default_pricetag/models/product_template.py#L148) but I am not sure about it's use
> 
> Can you test and check it out?
> I think it's probably a mistake

@ivantodorovich : when rename module from `product_to_print` to `product_print_category` field `category_print_id` is also renamed to `print_category_id`

do we need to keep that change or need to rename field same as before in version 9 ?

2020-04-15 09:40 UTC, ivantodorovich commented
Hi @ajayjaviya !

> do we need to keep that change or need to rename field same as before in version 9 ?

I don't understand exactly what you mean.
But we should have this module work with product_print_category, and be consistent with it.

According to what you say it seems we need to keep only `print_category_id`, right?

It also means we need to add a migration script to copy values from `category_print_id` to `print_category_id`. (I'll do it in the datbase migration script, no need to do it here)

2020-04-15 10:26 UTC, ajayjaviya commented
> Hi @ajayjaviya !
> 
> > do we need to keep that change or need to rename field same as before in version 9 ?
> 
> I don't understand exactly what you mean.
> But we should have this module work with product_print_category, and be consistent with it.
> 
> According to what you say it seems we need to keep only `print_category_id`, right?
> 
> It also means we need to add a migration script to copy values from `category_print_id` to `print_category_id`. (I'll do it in the datbase migration script, no need to do it here)

yes ,so do i  rename `category_print_id` to `print_category_id` ?

2020-04-15 10:40 UTC, ivantodorovich commented
Yes pls.
and analize why we're redefining this field because it seems it's already defined in product_print_category, right?

2020-04-15 11:22 UTC, ajayjaviya commented
> Yes pls.
> and analize why we're redefining this field because it seems it's already defined in product_print_category, right?

@ivantodorovich yes sure I will analize it.

2020-04-16 07:51 UTC, merged