12.0 mig coop inventory
druidoo/FoodCoops pull request #55
Opened 2020-02-20 15:49 UTC by krunal267

Task URL:

https://www.druidoo.io/web#id=1548&action=367&model=project.task&view_type=form&menu_id=237

2020-02-20 16:53 UTC, ivantodorovich requested changes

2020-02-20 16:53 UTC, ivantodorovich commented on purchase_package_qty/__manifest__.py
> +        # 'views/report_stockinventory.xml',
you're removing this view.

But also, why are we changing `purchase_package_qty`? that's not in the scope of this PR and that module is supposed to be working :thinking:

2020-02-20 17:23 UTC, krunal267 commented
Hi @ivantodorovich 

Please check the Travis, somehow it's failing due to purchase_package_qty module

2020-02-20 17:25 UTC, krunal267 commented
Should I do the changes in the same branch or create a new branch for the change in puchase_package_qty?

2020-02-24 11:32 UTC, krunal267 commented
Hi @ivantodorovich 

The branch is ready to merge :)

2020-02-24 12:05 UTC, merged