12.0 mig edi purchase base
druidoo/FoodCoops pull request #76
Opened 2020-03-04 07:11 UTC by chetanrdhaduk

Task URL:
https://www.druidoo.io/web#id=1742&action=367&model=project.task&view_type=form&menu_id=237

2020-03-04 12:18 UTC, ivantodorovich commented
Can you check why tests are failing with this module?

2020-03-04 12:46 UTC, ivantodorovich requested changes

2020-03-04 12:46 UTC, ivantodorovich commented on edi_purchase_base/models/purchase.py
>          oldname="minimum_planned_date",
```suggestion
```
This is not needed. If you find more occurrences like this, remove them

2020-03-04 12:46 UTC, ivantodorovich commented on edi_purchase_base/models/purchase.py
> +        required=False,
```suggestion
```
This is the default, right?

2020-03-04 12:46 UTC, ivantodorovich commented on edi_purchase_base/models/picking_update.py
> +    _name = "picking.edi"
```suggestion
    _name = "picking.edi"
    _description = "Picking EDI"
```

2020-03-04 12:46 UTC, ivantodorovich commented on edi_purchase_base/models/supplier_price_list.py
> +    _name = "supplier.price.list"
```suggestion
    _name = "supplier.price.list"
    _description = "Supplier Price List"
```

2020-03-04 12:50 UTC, chetanrdhaduk commented on edi_purchase_base/models/purchase.py
> +        required=False,
Yes, It's default

2020-03-04 13:00 UTC, ivantodorovich commented
The model picking.edi has no access rules, consider adding one. E.g. access_picking_edi,access_picking_edi,model_picking_edi,base.group_user,1,0,0,0

2020-03-05 15:51 UTC, ivantodorovich commented
If you can fix those warnings it would be great, that way we can track real warnings because apparently sometimes they report very critical things

```
2020-03-05 14:01:56,817 6424 WARNING openerp_test odoo.models: The model edi.mapping.lines has no _description
2020-03-05 14:01:56,817 6424 WARNING openerp_test odoo.models: The model edi.price.mapping has no _description
2020-03-05 14:01:56,818 6424 WARNING openerp_test odoo.models: The model edi.ble.mapping has no _description
2020-03-05 14:01:56,818 6424 WARNING openerp_test odoo.models: The model edi.config.system has no _description
```

2020-03-06 15:26 UTC, merged